###
GET  http://localhost:3000/reservations
Content-Type: application/json
###
POST http://localhost:3000/reservations
Content-Type: application/json

{
  "startDate": "12/20/2022",
  "endDate": "12/25/2022",
   "placeId": "54323",
   "invoiceId": "423"
}
###
GET  http://localhost:3000/reservations/65d96377f18cf948d203fe4e
Content-Type: application/json

###
POST  http://localhost:3001/users
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "ramdonstrongpassword123"
}