version: '3.1'

services:
  mongo:
    image: mongo:4.4.6
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo-net

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - mongo-net

  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    networks:
      - mongo-net

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge

volumes:
  mongodb_data:
